using System.Globalization;
using BlueMeter.Localization;
using BlueMeter.Plugins.Interfaces;
using BlueMeter.Properties;
using BlueMeter.Services;

namespace BlueMeter.Plugins.BuiltIn;

/// <summary>
/// Built-in plugin that exposes the World Boss tracker as a top-level entry in the
/// main view's plugin list.
///
/// Port notes (WPF -> Avalonia):
///   - Pure namespace rewrite. The Avalonia <see cref="IWindowManagementService"/>
///     is method-based (Phase 5 redesign), so <c>BossTrackerView.Show()</c> /
///     <c>SettingsView.Show()</c> become <see cref="IWindowManagementService.ShowBossTracker"/>
///     / <see cref="IWindowManagementService.ShowSettings"/>.
///   - <see cref="ResourcesKeys"/> is generated by Ihon.ResXKeyCodeGenerator from
///     Properties/Resources.resx and lives under <c>BlueMeter.Properties</c>.
/// </summary>
internal sealed class WorldBossPlugin(
    IWindowManagementService windowManagementService,
    LocalizationManager localizationManager) : IPlugin
{
    public string PackageName => "BlueMeter.Plugins.BuiltIn.WorldBossPlugin";

    public string PackageVersion => "3.0.0";

    public string GetPluginName(CultureInfo cultureInfo) =>
        localizationManager.GetString(ResourcesKeys.MainView_Plugin_WorldBoss_Title, cultureInfo);

    public string GetPluginDescription(CultureInfo cultureInfo) =>
        localizationManager.GetString(ResourcesKeys.MainView_Plugin_WorldBoss_Description, cultureInfo);

    public void OnRequestRun() => windowManagementService.ShowBossTracker();

    public void OnRequestSetting() => windowManagementService.ShowSettings();
}
