//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueMeter.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlueMeter.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 678150498 (Group 1).
        /// </summary>
        public static string About_Community_GroupOne {
            get {
                return ResourceManager.GetString("About_Community_GroupOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1022797551 (Group 2).
        /// </summary>
        public static string About_Community_GroupTwo {
            get {
                return ResourceManager.GetString("About_Community_GroupTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you cannot access GitHub or want to find teammates, join the Tencent QQ groups:.
        /// </summary>
        public static string About_Community_Invite {
            get {
                return ResourceManager.GetString("About_Community_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To contribute, please fork the repository and submit a pull request..
        /// </summary>
        public static string About_Contribution {
            get {
                return ResourceManager.GetString("About_Contribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2025 anying1073/StarResonanceDps Team..
        /// </summary>
        public static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尻鸭（ihonliu）.
        /// </summary>
        public static string About_Developer_Ihonliu {
            get {
                return ResourceManager.GetString("About_Developer_Ihonliu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 惊奇猫猫盒 (anying1073: project founder).
        /// </summary>
        public static string About_Developer_Lead {
            get {
                return ResourceManager.GetString("About_Developer_Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 青岚宗王腾.
        /// </summary>
        public static string About_Developer_QingLan {
            get {
                return ResourceManager.GetString("About_Developer_QingLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 露詩（Rocy-June）.
        /// </summary>
        public static string About_Developer_RocyJune {
            get {
                return ResourceManager.GetString("About_Developer_RocyJune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors for this release (in no particular order):.
        /// </summary>
        public static string About_Developers_Label {
            get {
                return ResourceManager.GetString("About_Developers_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool requires no client modifications and stays within the game&apos;s terms of service. It helps players understand combat data, reduce unnecessary effort, and improve the gameplay experience. Please do not use the results for power discrimination or any behaviour that harms the community..
        /// </summary>
        public static string About_Intro_Details {
            get {
                return ResourceManager.GetString("About_Intro_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A combat data analytics tool built for Star Resonance players..
        /// </summary>
        public static string About_Intro_Primary {
            get {
                return ResourceManager.GetString("About_Intro_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project is open source at.
        /// </summary>
        public static string About_OpenSource_Prefix {
            get {
                return ResourceManager.GetString("About_OpenSource_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/anying1073/StarResonanceDps.
        /// </summary>
        public static string About_OpenSource_RepositoryUrl {
            get {
                return ResourceManager.GetString("About_OpenSource_RepositoryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , If you encounter any issues, please open an issue there..
        /// </summary>
        public static string About_OpenSource_Suffix {
            get {
                return ResourceManager.GetString("About_OpenSource_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by .NET 8, Licensed under the GNU AGPL v3..
        /// </summary>
        public static string About_PoweredBy {
            get {
                return ResourceManager.GetString("About_PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks to.
        /// </summary>
        public static string About_Thanks_Prefix {
            get {
                return ResourceManager.GetString("About_Thanks_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/dmlgzs/StarResonanceDamageCounter.
        /// </summary>
        public static string About_Thanks_RepositoryUrl {
            get {
                return ResourceManager.GetString("About_Thanks_RepositoryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for supporting and inspiring this project..
        /// </summary>
        public static string About_Thanks_Suffix {
            get {
                return ResourceManager.GetString("About_Thanks_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version:.
        /// </summary>
        public static string About_Version_Label {
            get {
                return ResourceManager.GetString("About_Version_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close application?.
        /// </summary>
        public static string App_Exit_Confirm_Content {
            get {
                return ResourceManager.GetString("App_Exit_Confirm_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string App_Exit_Confirm_Title {
            get {
                return ResourceManager.GetString("App_Exit_Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StarResonance ToolBox.
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frost Mage.
        /// </summary>
        public static string Classes_FrostMage {
            get {
                return ResourceManager.GetString("Classes_FrostMage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Guardian.
        /// </summary>
        public static string Classes_HeavyGuardian {
            get {
                return ResourceManager.GetString("Classes_HeavyGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marksman.
        /// </summary>
        public static string Classes_Marksman {
            get {
                return ResourceManager.GetString("Classes_Marksman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield Knight.
        /// </summary>
        public static string Classes_ShieldKnight {
            get {
                return ResourceManager.GetString("Classes_ShieldKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul Musician.
        /// </summary>
        public static string Classes_SoulMusician {
            get {
                return ResourceManager.GetString("Classes_SoulMusician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stormblade.
        /// </summary>
        public static string Classes_Stormblade {
            get {
                return ResourceManager.GetString("Classes_Stormblade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdant Oracle.
        /// </summary>
        public static string Classes_VerdantOracle {
            get {
                return ResourceManager.GetString("Classes_VerdantOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Knight.
        /// </summary>
        public static string Classes_WindKnight {
            get {
                return ResourceManager.GetString("Classes_WindKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FrostBeam.
        /// </summary>
        public static string ClassSpec_FrostMageFrostBeam {
            get {
                return ResourceManager.GetString("ClassSpec_FrostMageFrostBeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icicle.
        /// </summary>
        public static string ClassSpec_FrostMageIcicle {
            get {
                return ResourceManager.GetString("ClassSpec_FrostMageIcicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string ClassSpec_HeavyGuardianBlock {
            get {
                return ResourceManager.GetString("ClassSpec_HeavyGuardianBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earthfort.
        /// </summary>
        public static string ClassSpec_HeavyGuardianEarthfort {
            get {
                return ResourceManager.GetString("ClassSpec_HeavyGuardianEarthfort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falconry.
        /// </summary>
        public static string ClassSpec_MarksmanFalconry {
            get {
                return ResourceManager.GetString("ClassSpec_MarksmanFalconry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wildpack.
        /// </summary>
        public static string ClassSpec_MarksmanWildpack {
            get {
                return ResourceManager.GetString("ClassSpec_MarksmanWildpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        public static string ClassSpec_ShieldKnightRecovery {
            get {
                return ResourceManager.GetString("ClassSpec_ShieldKnightRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield.
        /// </summary>
        public static string ClassSpec_ShieldKnightShield {
            get {
                return ResourceManager.GetString("ClassSpec_ShieldKnightShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concerto.
        /// </summary>
        public static string ClassSpec_SoulMusicianConcerto {
            get {
                return ResourceManager.GetString("ClassSpec_SoulMusicianConcerto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissonance.
        /// </summary>
        public static string ClassSpec_SoulMusicianDissonance {
            get {
                return ResourceManager.GetString("ClassSpec_SoulMusicianDissonance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IaidoSlash.
        /// </summary>
        public static string ClassSpec_StormbladeIaidoSlash {
            get {
                return ResourceManager.GetString("ClassSpec_StormbladeIaidoSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoonStrike.
        /// </summary>
        public static string ClassSpec_StormbladeMoonStrike {
            get {
                return ResourceManager.GetString("ClassSpec_StormbladeMoonStrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string ClassSpec_Unknown {
            get {
                return ResourceManager.GetString("ClassSpec_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LifeBind.
        /// </summary>
        public static string ClassSpec_VerdantOracleLifeBind {
            get {
                return ResourceManager.GetString("ClassSpec_VerdantOracleLifeBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smite.
        /// </summary>
        public static string ClassSpec_VerdantOracleSmite {
            get {
                return ResourceManager.GetString("ClassSpec_VerdantOracleSmite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skyward.
        /// </summary>
        public static string ClassSpec_WindKnightSkyward {
            get {
                return ResourceManager.GetString("ClassSpec_WindKnightSkyward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VanGuard.
        /// </summary>
        public static string ClassSpec_WindKnightVanGuard {
            get {
                return ResourceManager.GetString("ClassSpec_WindKnightVanGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string Common_Action_Open {
            get {
                return ResourceManager.GetString("Common_Action_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Common_Dash {
            get {
                return ResourceManager.GetString("Common_Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Classes.
        /// </summary>
        public static string DamageReference_Classes_All {
            get {
                return ResourceManager.GetString("DamageReference_Classes_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is for entertainment and reference only. Do not use it for power discrimination or any behaviour that harms the community; violations will result in permanent revocation..
        /// </summary>
        public static string DamageReference_Disclaimer {
            get {
                return ResourceManager.GetString("DamageReference_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Breakdown.
        /// </summary>
        public static string DamageReference_Header_Title {
            get {
                return ResourceManager.GetString("DamageReference_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data yet.
        /// </summary>
        public static string DamageReference_NoData {
            get {
                return ResourceManager.GetString("DamageReference_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Reference.
        /// </summary>
        public static string DamageReference_Ribbon_Title {
            get {
                return ResourceManager.GetString("DamageReference_Ribbon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Reference.
        /// </summary>
        public static string DamageReference_Table_Title {
            get {
                return ResourceManager.GetString("DamageReference_Table_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddSampleData.
        /// </summary>
        public static string Debug_AddSampleData {
            get {
                return ResourceManager.GetString("Debug_AddSampleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Test Log.
        /// </summary>
        public static string Debug_AddTestLog {
            get {
                return ResourceManager.GetString("Debug_AddTestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Scroll.
        /// </summary>
        public static string Debug_AutoScroll {
            get {
                return ResourceManager.GetString("Debug_AutoScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About View.
        /// </summary>
        public static string Debug_Button_About {
            get {
                return ResourceManager.GetString("Debug_Button_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Reference View.
        /// </summary>
        public static string Debug_Button_DamageReference {
            get {
                return ResourceManager.GetString("Debug_Button_DamageReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pcap Test.
        /// </summary>
        public static string Debug_Button_PcapTest {
            get {
                return ResourceManager.GetString("Debug_Button_PcapTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings View.
        /// </summary>
        public static string Debug_Button_Settings {
            get {
                return ResourceManager.GetString("Debug_Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Breakdown View.
        /// </summary>
        public static string Debug_Button_SkillBreakdown {
            get {
                return ResourceManager.GetString("Debug_Button_SkillBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Logs.
        /// </summary>
        public static string Debug_ClearLogs {
            get {
                return ResourceManager.GetString("Debug_ClearLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        public static string Debug_Filter_Label {
            get {
                return ResourceManager.GetString("Debug_Filter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string Debug_Filter_Level {
            get {
                return ResourceManager.GetString("Debug_Filter_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter logs by message or category content.
        /// </summary>
        public static string Debug_Filter_Tooltip {
            get {
                return ResourceManager.GetString("Debug_Filter_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug utilities.
        /// </summary>
        public static string Debug_Group_Title {
            get {
                return ResourceManager.GetString("Debug_Group_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Debug_Header_Category {
            get {
                return ResourceManager.GetString("Debug_Header_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Debug_Header_Level {
            get {
                return ResourceManager.GetString("Debug_Header_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Debug_Header_Message {
            get {
                return ResourceManager.GetString("Debug_Header_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Debug_Header_Time {
            get {
                return ResourceManager.GetString("Debug_Header_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load PCAP.
        /// </summary>
        public static string Debug_LoadPcap {
            get {
                return ResourceManager.GetString("Debug_LoadPcap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Debug_Localization_Apply {
            get {
                return ResourceManager.GetString("Debug_Localization_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Debug_Localization_Language {
            get {
                return ResourceManager.GetString("Debug_Localization_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Debug_Localization_Test {
            get {
                return ResourceManager.GetString("Debug_Localization_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Key:.
        /// </summary>
        public static string Debug_Localization_TestKey {
            get {
                return ResourceManager.GetString("Debug_Localization_TestKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Logs.
        /// </summary>
        public static string Debug_SaveLogs {
            get {
                return ResourceManager.GetString("Debug_SaveLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered: .
        /// </summary>
        public static string Debug_Status_FilteredPrefix {
            get {
                return ResourceManager.GetString("Debug_Status_FilteredPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  logs.
        /// </summary>
        public static string Debug_Status_FilteredSuffix {
            get {
                return ResourceManager.GetString("Debug_Status_FilteredSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last: .
        /// </summary>
        public static string Debug_Status_LastPrefix {
            get {
                return ResourceManager.GetString("Debug_Status_LastPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: .
        /// </summary>
        public static string Debug_Status_TotalPrefix {
            get {
                return ResourceManager.GetString("Debug_Status_TotalPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  logs.
        /// </summary>
        public static string Debug_Status_TotalSuffix {
            get {
                return ResourceManager.GetString("Debug_Status_TotalSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme switch test text.
        /// </summary>
        public static string Debug_ThemeTestText {
            get {
                return ResourceManager.GetString("Debug_ThemeTestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse click-through enabled.
        /// </summary>
        public static string DpsStatistics_Indicator_ClickThrough_Tooltip {
            get {
                return ResourceManager.GetString("DpsStatistics_Indicator_ClickThrough_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Always on Top.
        /// </summary>
        public static string DpsStatistics_Indicator_WindowTopMost_Tooltip {
            get {
                return ResourceManager.GetString("DpsStatistics_Indicator_WindowTopMost_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string DpsStatistics_TestButton_Content {
            get {
                return ResourceManager.GetString("DpsStatistics_TestButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Test Item.
        /// </summary>
        public static string DpsStatistics_TestButton_Tooltip {
            get {
                return ResourceManager.GetString("DpsStatistics_TestButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About View.
        /// </summary>
        public static string MainView_Debug_Button_About {
            get {
                return ResourceManager.GetString("MainView_Debug_Button_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Reference View.
        /// </summary>
        public static string MainView_Debug_Button_DamageReference {
            get {
                return ResourceManager.GetString("MainView_Debug_Button_DamageReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pcap Test.
        /// </summary>
        public static string MainView_Debug_Button_PcapTest {
            get {
                return ResourceManager.GetString("MainView_Debug_Button_PcapTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings View.
        /// </summary>
        public static string MainView_Debug_Button_Settings {
            get {
                return ResourceManager.GetString("MainView_Debug_Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Breakdown View.
        /// </summary>
        public static string MainView_Debug_Button_SkillBreakdown {
            get {
                return ResourceManager.GetString("MainView_Debug_Button_SkillBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug utilities.
        /// </summary>
        public static string MainView_Debug_Group_Title {
            get {
                return ResourceManager.GetString("MainView_Debug_Group_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme switch test text.
        /// </summary>
        public static string MainView_Debug_ThemeTest {
            get {
                return ResourceManager.GetString("MainView_Debug_ThemeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StarResonance ToolBox.
        /// </summary>
        public static string MainView_Header_Title {
            get {
                return ResourceManager.GetString("MainView_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Official] StarResonanceToolBox Team.
        /// </summary>
        public static string MainView_Plugin_Author_OfficialTeam {
            get {
                return ResourceManager.GetString("MainView_Plugin_Author_OfficialTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Off.
        /// </summary>
        public static string MainView_Plugin_AutoRunState_Disabled {
            get {
                return ResourceManager.GetString("MainView_Plugin_AutoRunState_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto On.
        /// </summary>
        public static string MainView_Plugin_AutoRunState_Enabled {
            get {
                return ResourceManager.GetString("MainView_Plugin_AutoRunState_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto start.
        /// </summary>
        public static string MainView_Plugin_AutoStart {
            get {
                return ResourceManager.GetString("MainView_Plugin_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides DPS statistics and skill breakdown tools.
        /// </summary>
        public static string MainView_Plugin_DpsTool_Description {
            get {
                return ResourceManager.GetString("MainView_Plugin_DpsTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS Toolkit.
        /// </summary>
        public static string MainView_Plugin_DpsTool_Title {
            get {
                return ResourceManager.GetString("MainView_Plugin_DpsTool_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string MainView_Plugin_Label_Author {
            get {
                return ResourceManager.GetString("MainView_Plugin_Label_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro:.
        /// </summary>
        public static string MainView_Plugin_Label_Intro {
            get {
                return ResourceManager.GetString("MainView_Plugin_Label_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickly calculates optimal module combinations.
        /// </summary>
        public static string MainView_Plugin_ModuleSolver_Description {
            get {
                return ResourceManager.GetString("MainView_Plugin_ModuleSolver_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Solver.
        /// </summary>
        public static string MainView_Plugin_ModuleSolver_Title {
            get {
                return ResourceManager.GetString("MainView_Plugin_ModuleSolver_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community-driven tracker for Pig Nabo routes and locations.
        /// </summary>
        public static string MainView_Plugin_PigTracker_Description {
            get {
                return ResourceManager.GetString("MainView_Plugin_PigTracker_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pig Nabo Status Tracker.
        /// </summary>
        public static string MainView_Plugin_PigTracker_Title {
            get {
                return ResourceManager.GetString("MainView_Plugin_PigTracker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string MainView_Plugin_Search_PlaceHolder {
            get {
                return ResourceManager.GetString("MainView_Plugin_Search_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainView_Plugin_Settings {
            get {
                return ResourceManager.GetString("MainView_Plugin_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string MainView_Plugin_State_Inactive {
            get {
                return ResourceManager.GetString("MainView_Plugin_State_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string MainView_Plugin_State_Running {
            get {
                return ResourceManager.GetString("MainView_Plugin_State_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin SDK coming soon!.
        /// </summary>
        public static string MainView_Plugin_ThirdPartySdkTips {
            get {
                return ResourceManager.GetString("MainView_Plugin_ThirdPartySdkTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crowdsourced live data for each channel&apos;s world boss status.
        /// </summary>
        public static string MainView_Plugin_WorldBoss_Description {
            get {
                return ResourceManager.GetString("MainView_Plugin_WorldBoss_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Boss Status Tracker.
        /// </summary>
        public static string MainView_Plugin_WorldBoss_Title {
            get {
                return ResourceManager.GetString("MainView_Plugin_WorldBoss_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string MainView_PluginList_Title {
            get {
                return ResourceManager.GetString("MainView_PluginList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Menu_History {
            get {
                return ResourceManager.GetString("Menu_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo Mode.
        /// </summary>
        public static string Menu_PersonalMode {
            get {
                return ResourceManager.GetString("Menu_PersonalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Every Fight.
        /// </summary>
        public static string Menu_Record_Always {
            get {
                return ResourceManager.GetString("Menu_Record_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore fights &lt; 1 min.
        /// </summary>
        public static string Menu_Record_Skip1Min {
            get {
                return ResourceManager.GetString("Menu_Record_Skip1Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore fights &lt; 2 min.
        /// </summary>
        public static string Menu_Record_Skip2Min {
            get {
                return ResourceManager.GetString("Menu_Record_Skip2Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Options.
        /// </summary>
        public static string Menu_RecordSettings {
            get {
                return ResourceManager.GetString("Menu_RecordSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Total Damage.
        /// </summary>
        public static string Menu_ShowTotal {
            get {
                return ResourceManager.GetString("Menu_ShowTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Diary.
        /// </summary>
        public static string Menu_SkillDiary {
            get {
                return ResourceManager.GetString("Menu_SkillDiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Display.
        /// </summary>
        public static string Menu_SkillDisplay {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string Menu_SkillDisplay_All {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 10.
        /// </summary>
        public static string Menu_SkillDisplay_Top10 {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_Top10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 15.
        /// </summary>
        public static string Menu_SkillDisplay_Top15 {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_Top15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 5.
        /// </summary>
        public static string Menu_SkillDisplay_Top5 {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_Top5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 8.
        /// </summary>
        public static string Menu_SkillDisplay_Top8 {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_Top8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Boss Only.
        /// </summary>
        public static string Menu_StatisticBoss {
            get {
                return ResourceManager.GetString("Menu_StatisticBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Mode.
        /// </summary>
        public static string Menu_Training {
            get {
                return ResourceManager.GetString("Menu_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme Training.
        /// </summary>
        public static string Menu_Training_Extreme {
            get {
                return ResourceManager.GetString("Menu_Training_Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faction Training.
        /// </summary>
        public static string Menu_Training_Faction {
            get {
                return ResourceManager.GetString("Menu_Training_Faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo Training.
        /// </summary>
        public static string Menu_Training_Personal {
            get {
                return ResourceManager.GetString("Menu_Training_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze modules.
        /// </summary>
        public static string ModuleSolve_Analyze_Button {
            get {
                return ResourceManager.GetString("ModuleSolve_Analyze_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude stats (conflicts with targets) [type to search].
        /// </summary>
        public static string ModuleSolve_ExcludeProperties_Title {
            get {
                return ResourceManager.GetString("ModuleSolve_ExcludeProperties_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired level:.
        /// </summary>
        public static string ModuleSolve_ExpectedLevel_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_ExpectedLevel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Solver.
        /// </summary>
        public static string ModuleSolve_Header_Title {
            get {
                return ResourceManager.GetString("ModuleSolve_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ModuleSolve_ModuleType_All {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        public static string ModuleSolve_ModuleType_Defense {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module type:.
        /// </summary>
        public static string ModuleSolve_ModuleType_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offense.
        /// </summary>
        public static string ModuleSolve_ModuleType_Offense {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Offense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string ModuleSolve_ModuleType_Support {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat 1:.
        /// </summary>
        public static string ModuleSolve_Property1_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property1_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat 2:.
        /// </summary>
        public static string ModuleSolve_Property2_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property2_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat 3:.
        /// </summary>
        public static string ModuleSolve_Property3_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property3_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat 4:.
        /// </summary>
        public static string ModuleSolve_Property4_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property4_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat 5:.
        /// </summary>
        public static string ModuleSolve_Property5_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property5_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat priority.
        /// </summary>
        public static string ModuleSolve_Sort_Attribute {
            get {
                return ResourceManager.GetString("ModuleSolve_Sort_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        public static string ModuleSolve_Sort_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Sort_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level priority.
        /// </summary>
        public static string ModuleSolve_Sort_Level {
            get {
                return ResourceManager.GetString("ModuleSolve_Sort_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target stats and levels (0 = default) [type to search].
        /// </summary>
        public static string ModuleSolve_TargetProperties_Title {
            get {
                return ResourceManager.GetString("ModuleSolve_TargetProperties_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After opening this window, change zone or relog before analyzing. Right-click a stat option to clear it..
        /// </summary>
        public static string ModuleSolve_UsingTip {
            get {
                return ResourceManager.GetString("ModuleSolve_UsingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMBT (Western).
        /// </summary>
        public static string NumberDisplay_KMB {
            get {
                return ResourceManager.GetString("NumberDisplay_KMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wan (East Asian).
        /// </summary>
        public static string NumberDisplay_Wan {
            get {
                return ResourceManager.GetString("NumberDisplay_Wan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string ScopeTime_Current {
            get {
                return ResourceManager.GetString("ScopeTime_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string ScopeTime_Total {
            get {
                return ResourceManager.GetString("ScopeTime_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard all changes? Unsaved changes will be lost..
        /// </summary>
        public static string Settings_CancelConfirm_Message {
            get {
                return ResourceManager.GetString("Settings_CancelConfirm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Changes.
        /// </summary>
        public static string Settings_CancelConfirm_Title {
            get {
                return ResourceManager.GetString("Settings_CancelConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear data after combat.
        /// </summary>
        public static string Settings_Combat_ClearAfterBattle {
            get {
                return ResourceManager.GetString("Settings_Combat_ClearAfterBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset on map change.
        /// </summary>
        public static string Settings_Combat_ClearAfterTeleport {
            get {
                return ResourceManager.GetString("Settings_Combat_ClearAfterTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        public static string Settings_Common_Seconds {
            get {
                return ResourceManager.GetString("Settings_Common_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number display mode.
        /// </summary>
        public static string Settings_Display_NumberMode {
            get {
                return ResourceManager.GetString("Settings_Display_NumberMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay opacity.
        /// </summary>
        public static string Settings_Display_Opacity {
            get {
                return ResourceManager.GetString("Settings_Display_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Heading {
            get {
                return ResourceManager.GetString("Settings_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow system.
        /// </summary>
        public static string Settings_Language_Auto {
            get {
                return ResourceManager.GetString("Settings_Language_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        public static string Settings_Language_Chinese {
            get {
                return ResourceManager.GetString("Settings_Language_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Settings_Language_English {
            get {
                return ResourceManager.GetString("Settings_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português (Brasil).
        /// </summary>
        public static string Settings_Language_Portuguese {
            get {
                return ResourceManager.GetString("Settings_Language_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Adapter.
        /// </summary>
        public static string Settings_NetworkAdapter_Label {
            get {
                return ResourceManager.GetString("Settings_NetworkAdapter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Settings_NetworkAdapterAutoSelect_Button {
            get {
                return ResourceManager.GetString("Settings_NetworkAdapterAutoSelect_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network adapter auto select failed, please check you have proper network connections.
        /// </summary>
        public static string Settings_NetworkAdapterAutoSelect_Failed {
            get {
                return ResourceManager.GetString("Settings_NetworkAdapterAutoSelect_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust manually when auto detection fails.
        /// </summary>
        public static string Settings_Section_Basic_Sub {
            get {
                return ResourceManager.GetString("Settings_Section_Basic_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Settings.
        /// </summary>
        public static string Settings_Section_Basic_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Basic_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Clear data after combat] resets only the current data, not the total..
        /// </summary>
        public static string Settings_Section_Combat_Sub {
            get {
                return ResourceManager.GetString("Settings_Section_Combat_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Settings.
        /// </summary>
        public static string Settings_Section_Combat_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Combat_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Settings_Section_Display_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the interface language.
        /// </summary>
        public static string Settings_Section_Language_Description {
            get {
                return ResourceManager.GetString("Settings_Section_Language_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Section_Language_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press [Delete] to clear the selected shortcut.
        /// </summary>
        public static string Settings_Section_Shortcut_Sub {
            get {
                return ResourceManager.GetString("Settings_Section_Shortcut_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string Settings_Section_Shortcut_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Shortcut_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize your own tool box.
        /// </summary>
        public static string Settings_Section_Theme_Description {
            get {
                return ResourceManager.GetString("Settings_Section_Theme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Settings.
        /// </summary>
        public static string Settings_Section_Theme_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Theme_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Data.
        /// </summary>
        public static string Settings_Shortcut_ClearData {
            get {
                return ResourceManager.GetString("Settings_Shortcut_ClearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus this box and press a shortcut (e.g. F9). Press Delete to clear..
        /// </summary>
        public static string Settings_Shortcut_ClearData_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Shortcut_ClearData_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Through.
        /// </summary>
        public static string Settings_Shortcut_MouseThrough {
            get {
                return ResourceManager.GetString("Settings_Shortcut_MouseThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus this box and press a shortcut (e.g. Ctrl+F6). Press Delete to clear..
        /// </summary>
        public static string Settings_Shortcut_MouseThrough_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Shortcut_MouseThrough_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on Top.
        /// </summary>
        public static string Settings_Shortcut_TopMost {
            get {
                return ResourceManager.GetString("Settings_Shortcut_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus this box and press a shortcut (e.g. Ctrl+F9). Press Delete to clear..
        /// </summary>
        public static string Settings_Shortcut_TopMost_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Shortcut_TopMost_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Settings_Switch_Off {
            get {
                return ResourceManager.GetString("Settings_Switch_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string Settings_Switch_On {
            get {
                return ResourceManager.GetString("Settings_Switch_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image.
        /// </summary>
        public static string Settings_Theme_BackgroundImage {
            get {
                return ResourceManager.GetString("Settings_Theme_BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image....
        /// </summary>
        public static string Settings_Theme_SelectImage {
            get {
                return ResourceManager.GetString("Settings_Theme_SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Color.
        /// </summary>
        public static string Settings_Theme_WindowColor {
            get {
                return ResourceManager.GetString("Settings_Theme_WindowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage distribution.
        /// </summary>
        public static string SkillBreakdown_Card_DamageDistribution {
            get {
                return ResourceManager.GetString("SkillBreakdown_Card_DamageDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realtime DPS/HPS/DTPS charts.
        /// </summary>
        public static string SkillBreakdown_Card_RealtimeChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Card_RealtimeChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill contribution chart.
        /// </summary>
        public static string SkillBreakdown_Card_ShareChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Card_ShareChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Breakdown.
        /// </summary>
        public static string SkillBreakdown_Header_Title {
            get {
                return ResourceManager.GetString("SkillBreakdown_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge: 190.
        /// </summary>
        public static string SkillBreakdown_Info_Badge {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level: 60.
        /// </summary>
        public static string SkillBreakdown_Info_Level {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Sample Name--.
        /// </summary>
        public static string SkillBreakdown_Info_Name {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power: 25000.
        /// </summary>
        public static string SkillBreakdown_Info_Power {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UID: 123456.
        /// </summary>
        public static string SkillBreakdown_Info_Uid {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Uid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average hit.
        /// </summary>
        public static string SkillBreakdown_Label_AverageDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_AverageDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical hits.
        /// </summary>
        public static string SkillBreakdown_Label_CritCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_CritCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical damage.
        /// </summary>
        public static string SkillBreakdown_Label_CritDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_CritDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crit rate.
        /// </summary>
        public static string SkillBreakdown_Label_CritRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_CritRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times hit.
        /// </summary>
        public static string SkillBreakdown_Label_DamageTakenCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_DamageTakenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS.
        /// </summary>
        public static string SkillBreakdown_Label_Dps {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_Dps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hits.
        /// </summary>
        public static string SkillBreakdown_Label_HitCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_HitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucky hits.
        /// </summary>
        public static string SkillBreakdown_Label_LuckCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_LuckCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucky damage.
        /// </summary>
        public static string SkillBreakdown_Label_LuckDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_LuckDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luck rate.
        /// </summary>
        public static string SkillBreakdown_Label_LuckRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_LuckRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal damage.
        /// </summary>
        public static string SkillBreakdown_Label_NormalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_NormalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total damage.
        /// </summary>
        public static string SkillBreakdown_Label_TotalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_TotalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagine a bar chart here.
        /// </summary>
        public static string SkillBreakdown_Placeholder_BarChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_BarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details placeholder.
        /// </summary>
        public static string SkillBreakdown_Placeholder_Details {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagine a data table here.
        /// </summary>
        public static string SkillBreakdown_Placeholder_Form {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph placeholder.
        /// </summary>
        public static string SkillBreakdown_Placeholder_Graph {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagine a line chart here.
        /// </summary>
        public static string SkillBreakdown_Placeholder_LineChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_LineChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagine a pie chart here.
        /// </summary>
        public static string SkillBreakdown_Placeholder_PieChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_PieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage distribution.
        /// </summary>
        public static string SkillBreakdown_Section_DamageDistribution {
            get {
                return ResourceManager.GetString("SkillBreakdown_Section_DamageDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage info.
        /// </summary>
        public static string SkillBreakdown_Section_DamageInfo {
            get {
                return ResourceManager.GetString("SkillBreakdown_Section_DamageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string SkillBreakdown_Tab_Details {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        public static string SkillBreakdown_Tab_Graph {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing.
        /// </summary>
        public static string SkillBreakdown_Tab_Healing {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS.
        /// </summary>
        public static string SkillBreakdown_Tab_Output {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string SkillBreakdown_Tab_Summary {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Taken.
        /// </summary>
        public static string SkillBreakdown_Tab_Tanking {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Tanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7106.
        /// </summary>
        public static string SkillBreakdown_Value_AverageDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_AverageDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string SkillBreakdown_Value_CritCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_CritCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.92K.
        /// </summary>
        public static string SkillBreakdown_Value_CritDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_CritDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.67%.
        /// </summary>
        public static string SkillBreakdown_Value_CritRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_CritRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string SkillBreakdown_Value_DamageTakenCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_DamageTakenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.01K.
        /// </summary>
        public static string SkillBreakdown_Value_Dps {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_Dps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string SkillBreakdown_Value_HitCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_HitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string SkillBreakdown_Value_LuckCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_LuckCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string SkillBreakdown_Value_LuckDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_LuckDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0%.
        /// </summary>
        public static string SkillBreakdown_Value_LuckRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_LuckRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.71K.
        /// </summary>
        public static string SkillBreakdown_Value_NormalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_NormalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42.64K.
        /// </summary>
        public static string SkillBreakdown_Value_TotalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_TotalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string StatisticType_Damage {
            get {
                return ResourceManager.GetString("StatisticType_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing.
        /// </summary>
        public static string StatisticType_Healing {
            get {
                return ResourceManager.GetString("StatisticType_Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC Dmg In.
        /// </summary>
        public static string StatisticType_NpcTakenDamage {
            get {
                return ResourceManager.GetString("StatisticType_NpcTakenDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dmg In.
        /// </summary>
        public static string StatisticType_TakenDamage {
            get {
                return ResourceManager.GetString("StatisticType_TakenDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle: Full / Current.
        /// </summary>
        public static string Tooltip_ToggleScope {
            get {
                return ResourceManager.GetString("Tooltip_ToggleScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Window_About_Title {
            get {
                return ResourceManager.GetString("Window_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 野外Boss状态查看器.
        /// </summary>
        public static string Window_BossTracker_Title {
            get {
                return ResourceManager.GetString("Window_BossTracker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Reference.
        /// </summary>
        public static string Window_DamageReference_Title {
            get {
                return ResourceManager.GetString("Window_DamageReference_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug View.
        /// </summary>
        public static string Window_Debug_Title {
            get {
                return ResourceManager.GetString("Window_Debug_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS Statistics.
        /// </summary>
        public static string Window_DpsStatistics_Title {
            get {
                return ResourceManager.GetString("Window_DpsStatistics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Solver.
        /// </summary>
        public static string Window_ModuleSolve_Title {
            get {
                return ResourceManager.GetString("Window_ModuleSolve_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Window_Settings_Title {
            get {
                return ResourceManager.GetString("Window_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Details.
        /// </summary>
        public static string Window_SkillBreakdown_Title {
            get {
                return ResourceManager.GetString("Window_SkillBreakdown_Title", resourceCulture);
            }
        }
    }
}
