//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueMeter.Assets.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlueMeter.Assets.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 678150498（1群）.
        /// </summary>
        internal static string About_Community_GroupOne {
            get {
                return ResourceManager.GetString("About_Community_GroupOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1022797551（2群）.
        /// </summary>
        internal static string About_Community_GroupTwo {
            get {
                return ResourceManager.GetString("About_Community_GroupTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法访问 GitHub 或者想要寻求游戏伙伴也可以加群：.
        /// </summary>
        internal static string About_Community_Invite {
            get {
                return ResourceManager.GetString("About_Community_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果你想为本项目贡献代码，欢迎 Fork 之后提交 Pull Request。.
        /// </summary>
        internal static string About_Contribution {
            get {
                return ResourceManager.GetString("About_Contribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2025 anying1073/StarResonanceDps Team..
        /// </summary>
        internal static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尻鸭（ihonliu）.
        /// </summary>
        internal static string About_Developer_Ihonliu {
            get {
                return ResourceManager.GetString("About_Developer_Ihonliu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 惊奇猫猫盒（anying1073：项目发起者）.
        /// </summary>
        internal static string About_Developer_Lead {
            get {
                return ResourceManager.GetString("About_Developer_Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 青岚宗王腾.
        /// </summary>
        internal static string About_Developer_QingLan {
            get {
                return ResourceManager.GetString("About_Developer_QingLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 露詩（Rocy-June）.
        /// </summary>
        internal static string About_Developer_RocyJune {
            get {
                return ResourceManager.GetString("About_Developer_RocyJune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前版本的开发者们（排名不分先后）:.
        /// </summary>
        internal static string About_Developers_Label {
            get {
                return ResourceManager.GetString("About_Developers_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该工具无需修改游戏客户端，不违反游戏服务条款。该工具旨在帮助玩家更好地理解战斗数据，减少不必要的精力消耗，提升游戏体验。使用该工具前，请确保不会将数据结果用于战力歧视等破坏游戏社区环境的行为。.
        /// </summary>
        internal static string About_Intro_Details {
            get {
                return ResourceManager.GetString("About_Intro_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一款专为《星痕共鸣》玩家打造的战斗数据统计工具。.
        /// </summary>
        internal static string About_Intro_Primary {
            get {
                return ResourceManager.GetString("About_Intro_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本项目于.
        /// </summary>
        internal static string About_OpenSource_Prefix {
            get {
                return ResourceManager.GetString("About_OpenSource_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/anying1073/StarResonanceDps.
        /// </summary>
        internal static string About_OpenSource_RepositoryUrl {
            get {
                return ResourceManager.GetString("About_OpenSource_RepositoryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中开源，如在使用中遇到问题可以直接提出 Issue。.
        /// </summary>
        internal static string About_OpenSource_Suffix {
            get {
                return ResourceManager.GetString("About_OpenSource_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by .NET 8, Licensed under the GNU AGPL v3..
        /// </summary>
        internal static string About_PoweredBy {
            get {
                return ResourceManager.GetString("About_PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在此感谢.
        /// </summary>
        internal static string About_Thanks_Prefix {
            get {
                return ResourceManager.GetString("About_Thanks_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/dmlgzs/StarResonanceDamageCounter.
        /// </summary>
        internal static string About_Thanks_RepositoryUrl {
            get {
                return ResourceManager.GetString("About_Thanks_RepositoryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目对于本项目的帮助于支持.
        /// </summary>
        internal static string About_Thanks_Suffix {
            get {
                return ResourceManager.GetString("About_Thanks_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前版本号：.
        /// </summary>
        internal static string About_Version_Label {
            get {
                return ResourceManager.GetString("About_Version_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AlimamaShuHeiTi {
            get {
                object obj = ResourceManager.GetObject("AlimamaShuHeiTi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ApplicationIcon_256x256 {
            get {
                object obj = ResourceManager.GetObject("ApplicationIcon_256x256", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cancel_hover {
            get {
                object obj = ResourceManager.GetObject("cancel_hover", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cancel_normal {
            get {
                object obj = ResourceManager.GetObject("cancel_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启.
        /// </summary>
        internal static string Common_Action_Open {
            get {
                return ResourceManager.GetString("Common_Action_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Common_Dash {
            get {
                return ResourceManager.GetString("Common_Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以上数据仅供娱乐与参考，严禁用于战力歧视等破坏游戏社区环境的行为；一经发现，永久取消该功能的使用资格。.
        /// </summary>
        internal static string DamageReference_Disclaimer {
            get {
                return ResourceManager.GetString("DamageReference_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Breakdown.
        /// </summary>
        internal static string DamageReference_Header_Title {
            get {
                return ResourceManager.GetString("DamageReference_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无数据.
        /// </summary>
        internal static string DamageReference_NoData {
            get {
                return ResourceManager.GetString("DamageReference_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全职业.
        /// </summary>
        internal static string DamageReference_Profession_All {
            get {
                return ResourceManager.GetString("DamageReference_Profession_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害参考.
        /// </summary>
        internal static string DamageReference_Ribbon_Title {
            get {
                return ResourceManager.GetString("DamageReference_Ribbon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害参考.
        /// </summary>
        internal static string DamageReference_Table_Title {
            get {
                return ResourceManager.GetString("DamageReference_Table_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg  xmlns=&quot;http://www.w3.org/2000/svg&quot;  width=&quot;24&quot;  height=&quot;24&quot;  viewBox=&quot;0 0 24 24&quot;  fill=&quot;none&quot;  stroke=&quot;currentColor&quot;  stroke-width=&quot;2&quot;  stroke-linecap=&quot;round&quot;  stroke-linejoin=&quot;round&quot;  class=&quot;icon icon-tabler icons-tabler-outline icon-tabler-chart-bar-popular&quot;&gt;&lt;path stroke=&quot;none&quot; d=&quot;M0 0h24v24H0z&quot; fill=&quot;none&quot;/&gt;&lt;path d=&quot;M3 13a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v6a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1z&quot; /&gt;&lt;path d=&quot;M9 9a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v10a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1z&quot; /&gt;&lt;path d=&quot;M15 5a1 1 0 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string data_display {
            get {
                return ResourceManager.GetString("data-display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddSampleData.
        /// </summary>
        internal static string Debug_AddSampleData {
            get {
                return ResourceManager.GetString("Debug_AddSampleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Test Log.
        /// </summary>
        internal static string Debug_AddTestLog {
            get {
                return ResourceManager.GetString("Debug_AddTestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Scroll.
        /// </summary>
        internal static string Debug_AutoScroll {
            get {
                return ResourceManager.GetString("Debug_AutoScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于窗口.
        /// </summary>
        internal static string Debug_Button_About {
            get {
                return ResourceManager.GetString("Debug_Button_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害参考窗口.
        /// </summary>
        internal static string Debug_Button_DamageReference {
            get {
                return ResourceManager.GetString("Debug_Button_DamageReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCAP 测试.
        /// </summary>
        internal static string Debug_Button_PcapTest {
            get {
                return ResourceManager.GetString("Debug_Button_PcapTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置窗口.
        /// </summary>
        internal static string Debug_Button_Settings {
            get {
                return ResourceManager.GetString("Debug_Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能详情窗口.
        /// </summary>
        internal static string Debug_Button_SkillBreakdown {
            get {
                return ResourceManager.GetString("Debug_Button_SkillBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Logs.
        /// </summary>
        internal static string Debug_ClearLogs {
            get {
                return ResourceManager.GetString("Debug_ClearLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        internal static string Debug_Filter_Label {
            get {
                return ResourceManager.GetString("Debug_Filter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        internal static string Debug_Filter_Level {
            get {
                return ResourceManager.GetString("Debug_Filter_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter logs by message or category content.
        /// </summary>
        internal static string Debug_Filter_Tooltip {
            get {
                return ResourceManager.GetString("Debug_Filter_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调试功能.
        /// </summary>
        internal static string Debug_Group_Title {
            get {
                return ResourceManager.GetString("Debug_Group_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Debug_Header_Category {
            get {
                return ResourceManager.GetString("Debug_Header_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Debug_Header_Level {
            get {
                return ResourceManager.GetString("Debug_Header_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Debug_Header_Message {
            get {
                return ResourceManager.GetString("Debug_Header_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Debug_Header_Time {
            get {
                return ResourceManager.GetString("Debug_Header_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load PCAP.
        /// </summary>
        internal static string Debug_LoadPcap {
            get {
                return ResourceManager.GetString("Debug_LoadPcap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Logs.
        /// </summary>
        internal static string Debug_SaveLogs {
            get {
                return ResourceManager.GetString("Debug_SaveLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 过滤：.
        /// </summary>
        internal static string Debug_Status_FilteredPrefix {
            get {
                return ResourceManager.GetString("Debug_Status_FilteredPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  条日志.
        /// </summary>
        internal static string Debug_Status_FilteredSuffix {
            get {
                return ResourceManager.GetString("Debug_Status_FilteredSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新：.
        /// </summary>
        internal static string Debug_Status_LastPrefix {
            get {
                return ResourceManager.GetString("Debug_Status_LastPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总计：.
        /// </summary>
        internal static string Debug_Status_TotalPrefix {
            get {
                return ResourceManager.GetString("Debug_Status_TotalPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  条日志.
        /// </summary>
        internal static string Debug_Status_TotalSuffix {
            get {
                return ResourceManager.GetString("Debug_Status_TotalSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题切换测试文本.
        /// </summary>
        internal static string Debug_ThemeTestText {
            get {
                return ResourceManager.GetString("Debug_ThemeTestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg t=&quot;1755665363494&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;6610&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M872 63.9H154c-19.9 0-36 16.1-36 36L98 794.6V885.6h0.8c5.8 41.9 41.7 74.2 85.2 74.2h708c19.9 0 36-16.1 36-36 0 0-43.7-10.7-43.7-47.7s43.7-52.4 43.7-52.4v-28.4-8.3h-0.2L908 99.9c0-19.9-16.1-36-36-36z m-109.3 248c19.9 0 36-16.1 36-36V107.6h65.8l19.6 679.3H141.9l19.6-679.3h446.4V276c0 19.9 16.1 36 36 36l59.4-30 59.4 29.9z m-111.1-52.8V107.6H755v151.5l-32-16. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string diaryIcon {
            get {
                return ResourceManager.GetString("diaryIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string DpsStatistics_TestButton_Content {
            get {
                return ResourceManager.GetString("DpsStatistics_TestButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加测试数据.
        /// </summary>
        internal static string DpsStatistics_TestButton_Tooltip {
            get {
                return ResourceManager.GetString("DpsStatistics_TestButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg t=&quot;1755061232067&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;25570&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M662.016 361.984V102.4H102.4v519.68h219.648V921.6H921.6V361.984z m-19.968 19.968v220.16H342.016v-220.16z m239.616 499.712H361.984v-239.616h320V401.92h199.68z&quot; p-id=&quot;25571&quot;&gt;&lt;/path&gt;&lt;/svg&gt;.
        /// </summary>
        internal static string exclude {
            get {
                return ResourceManager.GetString("exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flushed_hover {
            get {
                object obj = ResourceManager.GetObject("flushed_hover", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] flushed_normal {
            get {
                object obj = ResourceManager.GetObject("flushed_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] handoff_hover {
            get {
                object obj = ResourceManager.GetObject("handoff_hover", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] handoff_normal {
            get {
                object obj = ResourceManager.GetObject("handoff_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HarmonyOS_Sans {
            get {
                object obj = ResourceManager.GetObject("HarmonyOS_Sans", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HarmonyOS_Sans_SC_Bold {
            get {
                object obj = ResourceManager.GetObject("HarmonyOS_Sans_SC_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg t=&quot;1755131064483&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;11454&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M512.5 98.29c-227.84 0-412.54 184.7-412.54 412.54s184.7 412.54 412.54 412.54 412.54-184.7 412.54-412.54S740.34 98.29 512.5 98.29z m249.28 661.82c-32.4 32.4-70.1 57.82-112.08 75.58-43.42 18.37-89.59 27.68-137.21 27.68-47.62 0-93.78-9.31-137.2-27.68-41.97-17.75-79.68-43.18-112.08-75.58-32.4-32.4-57.82-70.1-75.58-112.08-18.37-43.42-27.68-89.59-27.68-137.21  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string historicalRecords {
            get {
                return ResourceManager.GetString("historicalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg t=&quot;1755130842851&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1025 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;7366&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M779 1024H595V827.6c0-14.4-11.6-26-26-26h-93.2c-14.4 0-26 11.8-26 26V1024H251c-54.8 0-99.4-44.6-99.4-99.4V600.2l-112.2-35-9-9c-26.6-26.6-26.6-69.6 0-96.2L470 20.4c12.8-12.8 29.8-20 48-20s35.2 7 48 20l439.6 439.8c12.8 12.8 20 30 19.8 48 0 18.2-7.2 35.2-20 48l-9 9L878 600.4v324.2c0.2 54.8-44.2 99.4-99 99.4z&quot; p-id=&quot;7367&quot;&gt;&lt;/path&gt;&lt;/svg&gt;.
        /// </summary>
        internal static string HomeIcon {
            get {
                return ResourceManager.GetString("HomeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hp_icon {
            get {
                object obj = ResourceManager.GetObject("hp_icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IconFont {
            get {
                object obj = ResourceManager.GetObject("IconFont", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] left_hover {
            get {
                object obj = ResourceManager.GetObject("left_hover", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] left_normal {
            get {
                object obj = ResourceManager.GetObject("left_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于窗口.
        /// </summary>
        internal static string MainView_Debug_Button_About {
            get {
                return ResourceManager.GetString("MainView_Debug_Button_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害参考窗口.
        /// </summary>
        internal static string MainView_Debug_Button_DamageReference {
            get {
                return ResourceManager.GetString("MainView_Debug_Button_DamageReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCAP 测试.
        /// </summary>
        internal static string MainView_Debug_Button_PcapTest {
            get {
                return ResourceManager.GetString("MainView_Debug_Button_PcapTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置窗口.
        /// </summary>
        internal static string MainView_Debug_Button_Settings {
            get {
                return ResourceManager.GetString("MainView_Debug_Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能详情窗口.
        /// </summary>
        internal static string MainView_Debug_Button_SkillBreakdown {
            get {
                return ResourceManager.GetString("MainView_Debug_Button_SkillBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调试功能.
        /// </summary>
        internal static string MainView_Debug_Group_Title {
            get {
                return ResourceManager.GetString("MainView_Debug_Group_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题切换测试文本.
        /// </summary>
        internal static string MainView_Debug_ThemeTest {
            get {
                return ResourceManager.GetString("MainView_Debug_ThemeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 别查我 D P S.
        /// </summary>
        internal static string MainView_Header_Title {
            get {
                return ResourceManager.GetString("MainView_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [官方] 别查我DPS 开发团队.
        /// </summary>
        internal static string MainView_Plugin_Author_OfficialTeam {
            get {
                return ResourceManager.GetString("MainView_Plugin_Author_OfficialTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自启动.
        /// </summary>
        internal static string MainView_Plugin_AutoStart {
            get {
                return ResourceManager.GetString("MainView_Plugin_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提供DPS统计、技能分解等功能.
        /// </summary>
        internal static string MainView_Plugin_DpsTool_Description {
            get {
                return ResourceManager.GetString("MainView_Plugin_DpsTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS工具.
        /// </summary>
        internal static string MainView_Plugin_DpsTool_Title {
            get {
                return ResourceManager.GetString("MainView_Plugin_DpsTool_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者：.
        /// </summary>
        internal static string MainView_Plugin_Label_Author {
            get {
                return ResourceManager.GetString("MainView_Plugin_Label_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简介：.
        /// </summary>
        internal static string MainView_Plugin_Label_Intro {
            get {
                return ResourceManager.GetString("MainView_Plugin_Label_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提供模组快速计算最优解功能.
        /// </summary>
        internal static string MainView_Plugin_ModuleSolver_Description {
            get {
                return ResourceManager.GetString("MainView_Plugin_ModuleSolver_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模组求解器.
        /// </summary>
        internal static string MainView_Plugin_ModuleSolver_Title {
            get {
                return ResourceManager.GetString("MainView_Plugin_ModuleSolver_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通过大量的玩家在线数据互助，提供小猪娜宝的线路与位置信息.
        /// </summary>
        internal static string MainView_Plugin_PigTracker_Description {
            get {
                return ResourceManager.GetString("MainView_Plugin_PigTracker_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小猪娜宝状态查看器.
        /// </summary>
        internal static string MainView_Plugin_PigTracker_Title {
            get {
                return ResourceManager.GetString("MainView_Plugin_PigTracker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通过大量的玩家在线数据互助，提供各线路的野外BOSS存活状态等信息.
        /// </summary>
        internal static string MainView_Plugin_WorldBoss_Description {
            get {
                return ResourceManager.GetString("MainView_Plugin_WorldBoss_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 野外BOSS状态查看器.
        /// </summary>
        internal static string MainView_Plugin_WorldBoss_Title {
            get {
                return ResourceManager.GetString("MainView_Plugin_WorldBoss_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件列表.
        /// </summary>
        internal static string MainView_PluginList_Title {
            get {
                return ResourceManager.GetString("MainView_PluginList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] minimize_normal {
            get {
                object obj = ResourceManager.GetObject("minimize_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg t=&quot;1755922612322&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;11643&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M440.507964 511.963431L92.738519 357.277337a63.849154 63.849154 0 0 0-60.045997 0A62.313263 62.313263 0 0 0 0 411.179773v394.723805a62.166988 62.166988 0 0 0 35.54489 56.315978l348.500821 154.905506a64.361117 64.361117 0 0 0 28.377402 6.8018 66.408971 66.408971 0 0 0 31.010356-8.849653 63.264053 63.264053 0 0 0 32.399971-53.975573V565.865867A63.629741 63 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string moduleIcon {
            get {
                return ResourceManager.GetString("moduleIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分析模组.
        /// </summary>
        internal static string ModuleSolve_Analyze_Button {
            get {
                return ResourceManager.GetString("ModuleSolve_Analyze_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排除词条（与目标词条冲突）[可输入文字索引].
        /// </summary>
        internal static string ModuleSolve_ExcludeProperties_Title {
            get {
                return ResourceManager.GetString("ModuleSolve_ExcludeProperties_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期望等级：.
        /// </summary>
        internal static string ModuleSolve_ExpectedLevel_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_ExpectedLevel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模组求解器.
        /// </summary>
        internal static string ModuleSolve_Header_Title {
            get {
                return ResourceManager.GetString("ModuleSolve_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部.
        /// </summary>
        internal static string ModuleSolve_ModuleType_All {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 防御模组.
        /// </summary>
        internal static string ModuleSolve_ModuleType_Defense {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模组类型：.
        /// </summary>
        internal static string ModuleSolve_ModuleType_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 攻击模组.
        /// </summary>
        internal static string ModuleSolve_ModuleType_Offense {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Offense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 辅助模组.
        /// </summary>
        internal static string ModuleSolve_ModuleType_Support {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性1：.
        /// </summary>
        internal static string ModuleSolve_Property1_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property1_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性2：.
        /// </summary>
        internal static string ModuleSolve_Property2_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property2_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性3：.
        /// </summary>
        internal static string ModuleSolve_Property3_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property3_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性4：.
        /// </summary>
        internal static string ModuleSolve_Property4_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property4_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性5：.
        /// </summary>
        internal static string ModuleSolve_Property5_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property5_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性优先.
        /// </summary>
        internal static string ModuleSolve_Sort_Attribute {
            get {
                return ResourceManager.GetString("ModuleSolve_Sort_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排序方式：.
        /// </summary>
        internal static string ModuleSolve_Sort_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Sort_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等级优先.
        /// </summary>
        internal static string ModuleSolve_Sort_Level {
            get {
                return ResourceManager.GetString("ModuleSolve_Sort_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标词条和等级（0为默认）[可输入文字索引].
        /// </summary>
        internal static string ModuleSolve_TargetProperties_Title {
            get {
                return ResourceManager.GetString("ModuleSolve_TargetProperties_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开此界面后需要过图或者重新登陆一次才能进行分析【右键属性选项为清空当前选项】.
        /// </summary>
        internal static string ModuleSolve_UsingTip {
            get {
                return ResourceManager.GetString("ModuleSolve_UsingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Npc {
            get {
                object obj = ResourceManager.GetObject("Npc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NpcWhite {
            get {
                object obj = ResourceManager.GetObject("NpcWhite", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ok_hover {
            get {
                object obj = ResourceManager.GetObject("ok_hover", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ok_normal {
            get {
                object obj = ResourceManager.GetObject("ok_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 冰魔导师.
        /// </summary>
        internal static string Profession_FrostMage {
            get {
                return ResourceManager.GetString("Profession_FrostMage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 巨刃守护者.
        /// </summary>
        internal static string Profession_HeavyGuardian {
            get {
                return ResourceManager.GetString("Profession_HeavyGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 神射手.
        /// </summary>
        internal static string Profession_Marksman {
            get {
                return ResourceManager.GetString("Profession_Marksman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 神盾骑士.
        /// </summary>
        internal static string Profession_ShieldKnight {
            get {
                return ResourceManager.GetString("Profession_ShieldKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 灵魂乐手.
        /// </summary>
        internal static string Profession_SoulMusician {
            get {
                return ResourceManager.GetString("Profession_SoulMusician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷影剑士.
        /// </summary>
        internal static string Profession_Stormblade {
            get {
                return ResourceManager.GetString("Profession_Stormblade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 森语者.
        /// </summary>
        internal static string Profession_VerdantOracle {
            get {
                return ResourceManager.GetString("Profession_VerdantOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 青岚骑士.
        /// </summary>
        internal static string Profession_WindKnight {
            get {
                return ResourceManager.GetString("Profession_WindKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg t=&quot;1755091003951&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1042 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;6442&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M581.632 697.344l126.976 0 0 194.56q0 33.792-10.24 58.88t-27.136 40.96-39.424 23.552-48.128 7.68l-452.608 0q-24.576 0-48.128-9.728t-41.472-27.136-29.184-40.96-11.264-52.224l0-706.56q0-24.576 11.776-47.104t30.208-39.936 40.96-28.16 45.056-10.752l449.536 0q26.624 0 50.176 11.776t41.472 29.696 28.16 40.448 10.24 44.032l0 188.416-126.976 0 1.024-195.584-452.6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quit {
            get {
                return ResourceManager.GetString("quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg t=&quot;1755404127609&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;6193&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M821.043 233.882c-7.065-0.512-13.926 2.048-18.944 7.065s-7.577 11.879-7.065 18.944v520.5c-1.844 27.75-23.86 49.97-51.61 52.019H289.69c-31.028 0-67.072-26.01-67.072-52.02v-58.265c0-26.01 31.027-41.984 62.054-41.984h433.254c7.066 0.512 13.927-2.048 18.944-7.066s7.578-11.878 7.066-18.944V228.864c0.512-26.726-10.445-52.429-30.31-70.349-19.764-18.022-46.388-26 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string reference {
            get {
                return ResourceManager.GetString("reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] right_hover {
            get {
                object obj = ResourceManager.GetObject("right_hover", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] right_normal {
            get {
                object obj = ResourceManager.GetObject("right_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SAOWelcomeTT {
            get {
                object obj = ResourceManager.GetObject("SAOWelcomeTT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg t=&quot;1724122928419&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;2893&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M920.5 435.9c-7.6-40.3-36.1-66.8-69.8-66.2h-3.4c-36.6 0-66.3-29.7-66.3-66.3 0-7.8 3.6-19.1 6-24.9 15.4-35.1 3.3-78.1-28.9-100.6l-102-56.9-4.2-2c-31.7-13.7-72.7-5.4-96.4 19.2-15.1 15.6-42.2 33.7-54.6 33.7-12.5 0-39.8-18.5-54.9-34.3-23.6-24.9-62.2-34.4-97.4-19.5l-105.4 57.7-4.2 2.7c-31.7 22-43.8 65.3-28.3 100.1 1.9 4.6 6 16.7 6 24.9 0 36.6-29.7 66.3-66.3 66 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string set_up {
            get {
                return ResourceManager.GetString("set_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setting_hover {
            get {
                object obj = ResourceManager.GetObject("setting_hover", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] setting_normal {
            get {
                object obj = ResourceManager.GetObject("setting_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害分布.
        /// </summary>
        internal static string SkillBreakdown_Card_DamageDistribution {
            get {
                return ResourceManager.GetString("SkillBreakdown_Card_DamageDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS/HPS/DTPS实时曲线图.
        /// </summary>
        internal static string SkillBreakdown_Card_RealtimeChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Card_RealtimeChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能占比分布图.
        /// </summary>
        internal static string SkillBreakdown_Card_ShareChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Card_ShareChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能详情.
        /// </summary>
        internal static string SkillBreakdown_Header_Title {
            get {
                return ResourceManager.GetString("SkillBreakdown_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 臂章: 190.
        /// </summary>
        internal static string SkillBreakdown_Info_Badge {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等级: 60.
        /// </summary>
        internal static string SkillBreakdown_Info_Level {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --测试名称--.
        /// </summary>
        internal static string SkillBreakdown_Info_Name {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 战力: 25000.
        /// </summary>
        internal static string SkillBreakdown_Info_Power {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UID: 123456.
        /// </summary>
        internal static string SkillBreakdown_Info_Uid {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Uid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均伤害.
        /// </summary>
        internal static string SkillBreakdown_Label_AverageDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_AverageDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暴击次数.
        /// </summary>
        internal static string SkillBreakdown_Label_CritCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_CritCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暴击伤害.
        /// </summary>
        internal static string SkillBreakdown_Label_CritDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_CritDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暴击率.
        /// </summary>
        internal static string SkillBreakdown_Label_CritRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_CritRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受击次数.
        /// </summary>
        internal static string SkillBreakdown_Label_DamageTakenCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_DamageTakenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒伤.
        /// </summary>
        internal static string SkillBreakdown_Label_Dps {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_Dps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 命中次数.
        /// </summary>
        internal static string SkillBreakdown_Label_HitCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_HitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幸运次数.
        /// </summary>
        internal static string SkillBreakdown_Label_LuckCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_LuckCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幸运伤害.
        /// </summary>
        internal static string SkillBreakdown_Label_LuckDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_LuckDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幸运率.
        /// </summary>
        internal static string SkillBreakdown_Label_LuckRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_LuckRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 普通伤害.
        /// </summary>
        internal static string SkillBreakdown_Label_NormalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_NormalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总伤害.
        /// </summary>
        internal static string SkillBreakdown_Label_TotalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_TotalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 假装这里有个条形图.
        /// </summary>
        internal static string SkillBreakdown_Placeholder_BarChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_BarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 详情占位.
        /// </summary>
        internal static string SkillBreakdown_Placeholder_Details {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 假装这里有个表单.
        /// </summary>
        internal static string SkillBreakdown_Placeholder_Form {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图表占位.
        /// </summary>
        internal static string SkillBreakdown_Placeholder_Graph {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 假装这里有个折线图.
        /// </summary>
        internal static string SkillBreakdown_Placeholder_LineChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_LineChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 假装这里有个饼图.
        /// </summary>
        internal static string SkillBreakdown_Placeholder_PieChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_PieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害信息.
        /// </summary>
        internal static string SkillBreakdown_Section_DamageInfo {
            get {
                return ResourceManager.GetString("SkillBreakdown_Section_DamageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string SkillBreakdown_Tab_Details {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph.
        /// </summary>
        internal static string SkillBreakdown_Tab_Graph {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 治疗.
        /// </summary>
        internal static string SkillBreakdown_Tab_Healing {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出.
        /// </summary>
        internal static string SkillBreakdown_Tab_Output {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string SkillBreakdown_Tab_Summary {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承伤.
        /// </summary>
        internal static string SkillBreakdown_Tab_Tanking {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Tanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7106.
        /// </summary>
        internal static string SkillBreakdown_Value_AverageDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_AverageDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string SkillBreakdown_Value_CritCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_CritCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.92K.
        /// </summary>
        internal static string SkillBreakdown_Value_CritDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_CritDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.67%.
        /// </summary>
        internal static string SkillBreakdown_Value_CritRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_CritRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string SkillBreakdown_Value_DamageTakenCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_DamageTakenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.01K.
        /// </summary>
        internal static string SkillBreakdown_Value_Dps {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_Dps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string SkillBreakdown_Value_HitCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_HitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string SkillBreakdown_Value_LuckCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_LuckCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string SkillBreakdown_Value_LuckDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_LuckDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0%.
        /// </summary>
        internal static string SkillBreakdown_Value_LuckRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_LuckRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.71K.
        /// </summary>
        internal static string SkillBreakdown_Value_NormalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_NormalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42.64K.
        /// </summary>
        internal static string SkillBreakdown_Value_TotalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_TotalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg t=&quot;1755060932429&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;19756&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M637.256674 18.797246c-24.996338-24.996338-65.590392-24.996338-90.586731 0l-239.964849 239.964849c-24.996338 24.996338-24.996338 65.590392 0 90.586731l31.995314 31.995313c24.996338 24.996338 65.590392 24.996338 90.58673 0l7.998828-7.998828 213.568716 213.368745-7.998828 7.998828c-24.996338 24.996338-24.996338 65.590392 0 90.58673l31.995313 31.995314c24.9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stakes {
            get {
                return ResourceManager.GetString("Stakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] top_hover {
            get {
                object obj = ResourceManager.GetObject("top_hover", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] top_normal {
            get {
                object obj = ResourceManager.GetObject("top_normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg t=&quot;1754590078301&quot; class=&quot;icon&quot; viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; p-id=&quot;8371&quot; width=&quot;200&quot; height=&quot;200&quot;&gt;&lt;path d=&quot;M619.064182 504.57971c91.163561-42.401656 154.766046-133.565217 154.766046-239.569358C773.830228 118.724638 655.10559 0 508.819876 0S243.809524 118.724638 243.809524 265.010352c0 106.004141 63.602484 197.167702 154.766045 239.569358C169.606625 555.461698 0 758.989648 0 1002.799172v21.200828h1017.639752v-21.200828c0-243.809524-169.606625-447.337474-398.575 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string userUid {
            get {
                return ResourceManager.GetString("userUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string Window_About_Title {
            get {
                return ResourceManager.GetString("Window_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伤害参考.
        /// </summary>
        internal static string Window_DamageReference_Title {
            get {
                return ResourceManager.GetString("Window_DamageReference_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug View.
        /// </summary>
        internal static string Window_Debug_Title {
            get {
                return ResourceManager.GetString("Window_Debug_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模组求解器.
        /// </summary>
        internal static string Window_ModuleSolve_Title {
            get {
                return ResourceManager.GetString("Window_ModuleSolve_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能详情.
        /// </summary>
        internal static string Window_SkillBreakdown_Title {
            get {
                return ResourceManager.GetString("Window_SkillBreakdown_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 伤害 {
            get {
                object obj = ResourceManager.GetObject("伤害", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 伤害白色 {
            get {
                object obj = ResourceManager.GetObject("伤害白色", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 冰魔导师 {
            get {
                object obj = ResourceManager.GetObject("冰魔导师", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 冰魔导师_Opacity10 {
            get {
                object obj = ResourceManager.GetObject("冰魔导师_Opacity10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 巨刃守护者 {
            get {
                object obj = ResourceManager.GetObject("巨刃守护者", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 巨刃守护者_Opacity10 {
            get {
                object obj = ResourceManager.GetObject("巨刃守护者_Opacity10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 承伤 {
            get {
                object obj = ResourceManager.GetObject("承伤", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 承伤白色 {
            get {
                object obj = ResourceManager.GetObject("承伤白色", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 森语者 {
            get {
                object obj = ResourceManager.GetObject("森语者", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 森语者_Opacity10 {
            get {
                object obj = ResourceManager.GetObject("森语者_Opacity10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 治疗 {
            get {
                object obj = ResourceManager.GetObject("治疗", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 治疗白色 {
            get {
                object obj = ResourceManager.GetObject("治疗白色", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 灵魂乐手 {
            get {
                object obj = ResourceManager.GetObject("灵魂乐手", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 灵魂乐手_Opacity10 {
            get {
                object obj = ResourceManager.GetObject("灵魂乐手_Opacity10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 皇冠 {
            get {
                object obj = ResourceManager.GetObject("皇冠", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 皇冠白 {
            get {
                object obj = ResourceManager.GetObject("皇冠白", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 神射手 {
            get {
                object obj = ResourceManager.GetObject("神射手", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 神射手_Opacity10 {
            get {
                object obj = ResourceManager.GetObject("神射手_Opacity10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 神盾骑士 {
            get {
                object obj = ResourceManager.GetObject("神盾骑士", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 神盾骑士_Opacity10 {
            get {
                object obj = ResourceManager.GetObject("神盾骑士_Opacity10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 雷影剑士 {
            get {
                object obj = ResourceManager.GetObject("雷影剑士", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 雷影剑士_Opacity10 {
            get {
                object obj = ResourceManager.GetObject("雷影剑士_Opacity10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 青岚骑士 {
            get {
                object obj = ResourceManager.GetObject("青岚骑士", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 青岚骑士_Opacity10 {
            get {
                object obj = ResourceManager.GetObject("青岚骑士_Opacity10", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
